# -*- coding: utf-8 -*-

from random import randint

data= [
{"us": "accommodation", "en": "accommodations"},
{"us": "action replay", "en": "instant replay"},
{"us": "aerofoil", "en": "airfoil"},
{"us": "aeroplane", "en": "airplane"},
{"us": "agony aunt", "en": "advice columnist"},
{"us": "Allen key", "en": "Allen wrench"},
{"us": "aluminium", "en": "aluminum"},
{"us": "aniseed", "en": "anise"},
{"us": "anticlockwise", "en": "counterclockwise"},
{"us": "articulated lorry", "en": "tractor-trailer"},
{"us": "asymmetric bars", "en": "uneven bars"},
{"us": "aubergine", "en": "eggplant"},
{"us": "baking tray", "en": "cookie sheet"},
{"us": "bank holiday", "en": "legal holiday"},
{"us": "beetroot", "en": "beet(s)"},
{"us": "biscuit", "en": "cookie; cracker"},
{"us": "black economy", "en": "underground economy"},
{"us": "blanket bath", "en": "sponge bath"},
{"us": "block of flats", "en": "apartment building"},
{"us": "boiler suit", "en": "coveralls"},
{"us": "bonnet (of a car)", "en": "hood"},
{"us": "boob tube", "en": "tube top"},
{"us": "boot (of a car)", "en": "trunk"},
{"us": "bottom drawer", "en": "hope chest"},
{"us": "bowls", "en": "lawn bowling"},
{"us": "braces", "en": "suspenders"},
{"us": "brawn (the food)", "en": "headcheese"},
{"us": "breakdown van", "en": "tow truck"},
{"us": "breeze block", "en": "cinder block"},
{"us": "bridging loan", "en": "bridge loan"},
{"us": "bumbag", "en": "fanny pack"},
{"us": "candyfloss", "en": "cotton candy"},
{"us": "car park", "en": "parking lot"},
{"us": "casualty", "en": "emergency room"},
{"us": "catapult", "en": "slingshot"},
{"us": "central reservation", "en": "median strip"},
{"us": "chemist", "en": "drugstore"},
{"us": "chips", "en": "French fries"},
{"us": "cinema", "en": "movie theater; the movies"},
{"us": "cling film", "en": "plastic wrap"},
{"us": "common seal", "en": "harbor seal"},
{"us": "consumer durables", "en": "durable goods"},
{"us": "cornflour", "en": "cornstarch"},
{"us": "cos (lettuce)", "en": "Romaine"},
{"us": "cot", "en": "crib"},
{"us": "cot death", "en": "crib death"},
{"us": "cotton bud", "en": "cotton swab"},
{"us": "cotton wool", "en": "absorbent cotton"},
{"us": "council estate", "en": "(housing) project"},
{"us": "courgette", "en": "zucchini"},
{"us": "court card", "en": "face card"},
{"us": "crash barrier", "en": "guardrail"},
{"us": "crisps", "en": "chips; potato chips"},
{"us": "crocodile clip", "en": "alligator clip"},
{"us": "cross-ply", "en": "bias-ply"},
{"us": "crotchet (music)", "en": "quarter note"},
{"us": "current account", "en": "checking account"},
{"us": "danger money", "en": "hazard pay"},
{"us": "demister (in a car)", "en": "defroster"},
{"us": "dialling tone", "en": "dial tone"},
{"us": "diamante", "en": "rhinestone"},
{"us": "double cream", "en": "heavy cream"},
{"us": "draughts (game)", "en": "checkers"},
{"us": "drawing pin", "en": "thumbtack"},
{"us": "dressing gown", "en": "robe; bathrobe"},
{"us": "drink-driving", "en": "drunk driving"},
{"us": "drinks cupboard", "en": "liquor cabinet"},
{"us": "drinks party", "en": "cocktail party"},
{"us": "driving licence", "en": "driver’s license"},
{"us": "dual carriageway", "en": "divided highway"},
{"us": "dummy (for a baby)", "en": "pacifier"},
{"us": "dust sheet", "en": "drop cloth"},
{"us": "dustbin", "en": "garbage can"},
{"us": "earth (electrical)", "en": "ground"},
{"us": "engaged (of a phone)", "en": "busy"},
{"us": "estate agent", "en": "real estate agent, realtor (trademark)"},
{"us": "estate car", "en": "station wagon"},
{"us": "ex-directory", "en": "unlisted"},
{"us": "faith school", "en": "parochial school"},
{"us": "financial year", "en": "fiscal year"},
{"us": "fire brigade/service", "en": "fire company/department"},
{"us": "first floor", "en": "second floor"},
{"us": "fish finger", "en": "fish stick"},
{"us": "fitted carpet", "en": "wall-to-wall carpeting"},
{"us": "flannel", "en": "washcloth"},
{"us": "flat", "en": "apartment"},
{"us": "flexitime", "en": "flextime"},
{"us": "flick knife", "en": "switchblade"},
{"us": "flyover", "en": "overpass"},
{"us": "football", "en": "soccer"},
{"us": "footway", "en": "sidewalk"},
{"us": "fringe (hair)", "en": "bangs"},
{"us": "full stop (punctuation)", "en": "period"},
{"us": "garden", "en": "yard; lawn"},
{"us": "gearing (finance)", "en": "leverage"},
{"us": "gear lever", "en": "gearshift"},
{"us": "goods train", "en": "freight train"},
{"us": "greaseproof paper", "en": "wax paper/waxed paper"},
{"us": "green fingers", "en": "green thumb"},
{"us": "grill (noun)", "en": "broiler"},
{"us": "grill (verb)", "en": "broil"},
{"us": "ground floor", "en": "first floor"},
{"us": "groundsman", "en": "groundskeeper"},
{"us": "hairslide", "en": "barrette"},
{"us": "hatstand", "en": "hatrack"},
{"us": "hen night", "en": "bachelorette party"},
{"us": "hire purchase", "en": "installment plan"},
{"us": "hoarding", "en": "billboard"},
{"us": "hob", "en": "stovetop"},
{"us": "holdall", "en": "carryall"},
{"us": "holiday", "en": "vacation"},
{"us": "holidaymaker", "en": "vacationer"},
{"us": "homely", "en": "homey"},
{"us": "hosepipe", "en": "(garden) hose"},
{"us": "in hospital", "en": "in the hospital"},
{"us": "hot flush", "en": "hot flash"},
{"us": "housing estate", "en": "housing development"},
{"us": "hundreds and thousands", "en": "sprinkles (for ice cream)"},
{"us": "ice lolly", "en": "Popsicle (trademark)"},
{"us": "icing sugar", "en": "confectioners’ sugar"},
{"us": "indicator (on a car)", "en": "turn signal"},
{"us": "inside leg", "en": "inseam"},
{"us": "jelly babies", "en": "jelly beans"},
{"us": "Joe Bloggs", "en": "Joe Blow"},
{"us": "Joe Public", "en": "John Q. Public"},
{"us": "jumble sale", "en": "rummage sale"},
{"us": "jump lead", "en": "jumper cable"},
{"us": "jumper", "en": "sweater"},
{"us": "junior school", "en": "elementary school"},
{"us": "kennel", "en": "doghouse"},
{"us": "ladybird", "en": "ladybug"},
{"us": "a lettuce", "en": "a head of lettuce"},
{"us": "level crossing", "en": "grade crossing"},
{"us": "lift", "en": "elevator"},
{"us": "lolly", "en": "lollipop"},
{"us": "lollipop lady (or man)", "en": "crossing guard"},
{"us": "loose cover", "en": "slipcover"},
{"us": "lorry", "en": "truck"},
{"us": "loudhailer", "en": "bullhorn"},
{"us": "low loader", "en": "flatbed truck"},
{"us": "lucky dip", "en": "grab bag"},
{"us": "luggage van", "en": "baggage car"},
{"us": "maize", "en": "corn"},
{"us": "mangetout", "en": "snow pea"},
{"us": "market garden", "en": "truck farm"},
{"us": "marshalling yard", "en": "railroad yard"},
{"us": "maths", "en": "math"},
{"us": "metalled road", "en": "paved road"},
{"us": "milometer", "en": "odometer"},
{"us": "minim (music)", "en": "half note"},
{"us": "mobile phone", "en": "cell phone"},
{"us": "monkey tricks", "en": "monkeyshines"},
{"us": "motorway", "en": "expressway; highway"},
{"us": "mum/mummy", "en": "mom/mommy"},
{"us": "nappy", "en": "diaper"},
{"us": "needlecord", "en": "pinwale"},
{"us": "newsreader", "en": "newscaster"},
{"us": "noughts and crosses", "en": "tic-tac-toe"},
{"us": "number plate", "en": "license plate"},
{"us": "off-licence", "en": "liquor store; package store"},
{"us": "opencast mining", "en": "open-pit mining"},
{"us": "ordinary share", "en": "common stock"},
{"us": "oven glove", "en": "oven mitt"},
{"us": "paddling pool", "en": "wading pool"},
{"us": "paracetamol", "en": "acetaminophen"},
{"us": "parting (in hair)", "en": "part"},
{"us": "patience", "en": "solitaire"},
{"us": "pavement", "en": "sidewalk"},
{"us": "pay packet", "en": "pay envelope"},
{"us": "pedestrian crossing", "en": "crosswalk"},
{"us": "peg", "en": "clothespin"},
{"us": "pelmet", "en": "valance"},
{"us": "petrol", "en": "gas; gasoline"},
{"us": "physiotherapy", "en": "physical therapy"},
{"us": "pinafore dress", "en": "jumper"},
{"us": "plain chocolate", "en": "dark chocolate"},
{"us": "plain flour", "en": "all-purpose flour"},
{"us": "polo neck", "en": "turtleneck"},
{"us": "positive discrimination", "en": "reverse discrimination"},
{"us": "postal vote", "en": "absentee ballot"},
{"us": "postbox", "en": "mailbox"},
{"us": "postcode", "en": "zip code"},
{"us": "potato crisp", "en": "potato chip"},
{"us": "power point", "en": "electrical outlet"},
{"us": "pram", "en": "baby carriage; stroller"},
{"us": "press stud", "en": "snap"},
{"us": "press-up", "en": "pushup"},
{"us": "private soldier", "en": "GI"},
{"us": "public school", "en": "private school"},
{"us": "public transport", "en": "public transportation"},
{"us": "punchbag", "en": "punching bag"},
{"us": "pushchair", "en": "stroller"},
{"us": "pylon", "en": "utility pole"},
{"us": "quantity surveyor", "en": "estimator"},
{"us": "quaver (music)", "en": "eighth note"},
{"us": "queue", "en": "line"},
{"us": "racing car", "en": "race car"},
{"us": "railway", "en": "railroad"},
{"us": "real tennis", "en": "court tennis"},
{"us": "recorded delivery", "en": "certified mail"},
{"us": "registration plate", "en": "license plate"},
{"us": "remould (tyre)", "en": "retread"},
{"us": "reverse the charges", "en": "call collect"},
{"us": "reversing lights", "en": "back-up lights"},
{"us": "right-angled triangle", "en": "right triangle"},
{"us": "ring road", "en": "beltway"},
{"us": "roundabout(at a fair)", "en": "carousel"},
{"us": "roundabout (in road)", "en": "traffic circle"},
{"us": "rowing boat", "en": "rowboat"},
{"us": "sailing boat", "en": "sailboat"},
{"us": "saloon (car)", "en": "sedan"},
{"us": "sandpit", "en": "sandbox"},
{"us": "sandwich cake", "en": "layer cake"},
{"us": "sanitary towel", "en": "sanitary napkin"},
{"us": "self-raising flour", "en": "self-rising flour"},
{"us": "semibreve (music)", "en": "whole note"},
{"us": "semitone(music)", "en": "half step"},
{"us": "share option", "en": "stock option"},
{"us": "shopping trolley", "en": "shopping cart"},
{"us": "show house/home", "en": "model home"},
{"us": "silencer (on a car)", "en": "muffler"},
{"us": "silverside", "en": "rump roast"},
{"us": "skeleton in the cupboard", "en": "skeleton in the closet"},
{"us": "skimmed milk", "en": "skim milk"},
{"us": "skipping rope", "en": "jump rope"},
{"us": "skirting board", "en": "baseboard"},
{"us": "sledge", "en": "sled"},
{"us": "sleeper", "en": "railroad tie"},
{"us": "sleeping partner", "en": "silent partner"},
{"us": "slowcoach", "en": "slowpoke"},
{"us": "snakes and ladders", "en": "chutes and ladders"},
{"us": "solicitor", "en": "lawyer"},
{"us": "soya/soya bean", "en": "soy/soybean"},
{"us": "splashback", "en": "backsplash"},
{"us": "spring onion", "en": "scallion"},
{"us": "stag night", "en": "bachelor party"},
{"us": "Stanley knife", "en": "utility knife"},
{"us": "starter", "en": "appetizer"},
{"us": "state school", "en": "public school"},
{"us": "storm in a teacup", "en": "tempest in a teapot"},
{"us": "surtitle", "en": "supertitle"},
{"us": "swede", "en": "rutabaga"},
{"us": "sweet(s)", "en": "candy"},
{"us": "takeaway (food)", "en": "takeout; to go"},
{"us": "taxi rank", "en": "taxi stand"},
{"us": "tea towel", "en": "dish towel"},
{"us": "terrace house", "en": "row house"},
{"us": "tick", "en": "check mark"},
{"us": "ticket tout", "en": "scalper"},
{"us": "timber", "en": "lumber"},
{"us": "titbit", "en": "tidbit"},
{"us": "toffee apple", "en": "candy apple or caramel apple"},
{"us": "touch wood", "en": "knock on wood"},
{"us": "trade union", "en": "labor union"},
{"us": "trading estate", "en": "industrial park"},
{"us": "trainers", "en": "sneakers"},
{"us": "transport cafe", "en": "truck stop"},
{"us": "trolley", "en": "shopping cart"},
{"us": "twelve-bore", "en": "twelve-gauge"},
{"us": "underground", "en": "subway"},
{"us": "vacuum flask", "en": "thermos bottle"},
{"us": "verge (of a road)", "en": "shoulder"},
{"us": "vest", "en": "undershirt"},
{"us": "veterinary surgeon", "en": "veterinarian"},
{"us": "wagon (on a train)", "en": "car"},
{"us": "waistcoat", "en": "vest"},
{"us": "walking frame", "en": "walker"},
{"us": "wardrobe", "en": "closet"},
{"us": "water ice", "en": "Italian ice"},
{"us": "weatherboard", "en": "clapboard"},
{"us": "white coffee", "en": "coffee with cream"},
{"us": "white spirit", "en": "mineral spirits"},
{"us": "wholemeal bread", "en": "wholewheat bread"},
{"us": "windcheater", "en": "windbreaker"},
{"us": "windscreen", "en": "windshield"},
{"us": "wing (of a car)", "en": "fender"},
{"us": "worktop", "en": "countertop"},
{"us": "zebra crossing", "en": "crosswalk"},
{"us": "zed (letter Z)", "en": "zee"},
{"us": "zip", "en": "zipper"},
    ]

class RandomEnUsDiff(object):
	"""
	{'en': str, 'us': str}
	"""

	def __init__(self):
		self.data = data

	def __str__(self):
		w = self.__get_word()
		return "%s (en) <-> %s (us) " % (w['en'], w['us'])

	def __get_word(self):
		return self.data[randint(0, len(self.data) - 1)]

	def get(self):
		return self.__get_word()
